[package]
name = "trussed-usbip"
version = "0.0.1"
authors = ["Nicolas Stalder <n@stalder.io>", "Conor Patrick <conor@solokeys.com>", "Szczepan Zalega <szczepan@nitrokey.com>"]
edition = "2021"

[dependencies]
interchange = "0.2.0"
log = { version = "0.4.14", default-features = false }
trussed = { version = "0.1", features = ["virt"] }
usb-device = { version = "0.2.7", default-features = false }
usbip-device = "0.1.4"

# ctaphid
ctaphid-dispatch = { version = "0.1", optional = true }
usbd-ctaphid = { git = "https://github.com/Nitrokey/nitrokey-3-firmware", optional = true }

[dev-dependencies]
clap = { version = "3.0.0", features = ["derive"] }
clap-num = "1.0.0"
pretty_env_logger = "0.4.0"
trussed = { version = "0.1", features = ["clients-3"] }

# applications
admin-app = { version = "0.1", features = ["log-all"] }
fido-authenticator = { version = "0.1", features = ["dispatch", "log-all"] }

[features]
default = ["ctaphid"]
ctaphid = ["ctaphid-dispatch", "usbd-ctaphid"]

[[example]]
name = "fido"
required-features = ["ctaphid"]

[patch.crates-io]
trussed = { git = "https://github.com/trussed-dev/trussed", rev = "3da56d8" }
